---
# tasks file for ntp
- name: Check current timezone
  shell: 'readlink /etc/localtime | cut -f6 -d"/"'
  register: current_zone
  changed_when: false
- name: Set Europe/Paris timezone
  file: src=/usr/share/zoneinfo/{{ntp_zone}}/{{ntp_city}}  dest=/etc/localtime state=link force=yes
  when: current_zone.stdout != '{{ntp_city}}'
- name: Ensure ntp is installed
  yum: name=ntp state=installed
- name: Ensure NTP is running.
  service: name=ntpd state=started enabled=yes
